[package]
name = "cad-dsl"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.4"
chumsky = "0.12.0"
clap = { version = "4.5.53", features = ["derive"] }
logos = "0.16.0"
subenum = "1.1"

[dev-dependencies]
assert_matches = "1.5"
